name: Jonathan Manfield
description: Blog
meta_description: "Jonathan Manfield Blog"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://jonathanmanfield.github.io'
google_analytics: 'UA-84071562-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://jonathanmanfield.github.io'
author:         'Jonathan Manfield'
authorTwitter:  'densekernel'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
